### ISSUE TITLE
Subdomain theme: People plugin

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu-core#1]
@kpettinga At Dave's suggestion, I'm posting issues with the subdomain themes here.

The people post type now shows on the backend, and the profiles shortcode works, but the actual profile page (meaning, when you click "View Profile" or you try to view directly from the profile admin page) gives a 404 error.

ex. This is a profile that Lorraine created on a subdomain site - the info shows when the profiles shortcode is used, but the actual profile page gives an error:
https://research.cgu.edu/tei/people/paul-thomas/

**Comment by davekellam** [comment]
This appears to be working now. I imagine the permalink structure hadn't been set/updated.
