### ISSUE TITLE
Subdomain theme: header carousels missing

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu-core#2]
With the new design changes, the option for the header carousel on a page has disappeared. Some of the subdomain sites were using this, so we'd like to add it back.

**Comment by davekellam** [comment]
Think I have this working again.

**Comment by holliscooper-cgu** [comment]
Do we need to redeploy the template files to the different WP installs again? We're not seeing the option yet.

**Comment by davekellam** [comment]
Ahh, yes. I didn't realize there wasn't any sort of auto-deployment setup. We use our [deploybot](http://deploybot.io/) account to deploy the main theme to cgu.edu.

**Comment by kpettinga** [comment]
@davekellam, @holliscooper-cgu 
Yes we need to re-upload the theme to all the different sites that use it.

There's too many sites using the core theme to setup a Deploybot environment for it.

Dave, we need to run `grunt build` to (re)create /release/cgu-core.zip. 

That file can be use to re-upload the theme on all the different sites that use it.

**Comment by holliscooper-cgu** [comment]
When you've got the new zip file, please email it just to me (not Greg) - I will make sure it gets deployed correctly. Thanks!

**Comment by davekellam** [comment]
Ran the build earlier, but hadn't had a chance to email Greg. You can find the zip file here: https://github.com/ObjectiveSubject/cgu-core/raw/master/release/cgu-core.zip
